"""esquema inicial

Revision ID: d913988b8355
Revises: 
Create Date: 2026-09-09 14:41:05.194175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd913988b8355'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genero',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=True),
    sa.Column('apellido_materno', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('estado',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('pais_id', sa.String(length=6), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clasificacion_id', sa.String(length=5), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_lanzamiento', sa.Date(), nullable=True),
    sa.CheckConstraint('precio > 0', name='chk_precio_vid'),
    sa.ForeignKeyConstraint(['clasificacion_id'], ['clasificacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.String(length=6), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plataforma',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colonia',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colonia_id', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=True),
    sa.Column('apellido_materno', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['calle_id'], ['calle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('numero_exterior', sa.String(length=10), nullable=False),
    sa.Column('numero_interior', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['calle_id'], ['calle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calle_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('puesto', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['calle_id'], ['calle.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curp'),
    sa.UniqueConstraint('rfc')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma_id', sa.String(length=50), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.CheckConstraint('stock >= 0', name='chk_stock_min'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataforma.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.CheckConstraint("metodo_pago IN ('Efectivo', 'Tarjeta', 'Transferencia')", name='chk_metodo_pago'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('videojuego_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='chk_cantidad_ven'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_venta')
    op.drop_table('venta')
    op.drop_table('telefono')
    op.drop_table('correo')
    op.drop_table('inventario')
    op.drop_table('empleado')
    op.drop_table('sucursal')
    op.drop_table('cliente')
    op.drop_table('calle')
    op.drop_table('colonia')
    op.drop_table('plataforma')
    op.drop_table('ciudad')
    op.drop_table('videojuego')
    op.drop_table('estado')
    op.drop_table('proveedor')
    op.drop_table('pais')
    op.drop_table('genero')
    op.drop_table('clasificacion')
    # ### end Alembic commands ###
